#ifndef RUNTIME_CONTRACT_COMMON_H
#define RUNTIME_CONTRACT_COMMON_H

#include <stdbool.h>
#include <stdint.h>

#define PLATFORM_JOINT_MOTOR_COUNT 4
#define PLATFORM_WHEEL_MOTOR_COUNT 2
#define PLATFORM_RC_CHANNEL_COUNT 8
#define PLATFORM_RC_SWITCH_COUNT 4

typedef enum {
  PLATFORM_FRAME_BODY = 0,
  PLATFORM_FRAME_WORLD = 1,
} platform_velocity_frame_t;

typedef enum {
  PLATFORM_ROBOT_MODE_IDLE = 0,
  PLATFORM_ROBOT_MODE_ACTIVE = 1,
  PLATFORM_ROBOT_MODE_RECOVER = 2,
  PLATFORM_ROBOT_MODE_JUMP = 3,
  PLATFORM_ROBOT_MODE_SAFE = 4,
} platform_robot_mode_t;

typedef enum {
  PLATFORM_MOTOR_KIND_JOINT = 0,
  PLATFORM_MOTOR_KIND_WHEEL = 1,
} platform_motor_kind_t;

typedef enum {
  PLATFORM_MOTOR_CONTROL_DISABLED = 0,
  PLATFORM_MOTOR_CONTROL_CURRENT = 1,
  PLATFORM_MOTOR_CONTROL_TORQUE = 2,
  PLATFORM_MOTOR_CONTROL_VELOCITY = 3,
  PLATFORM_MOTOR_CONTROL_POSITION = 4,
  PLATFORM_MOTOR_CONTROL_IMPEDANCE = 5,
} platform_motor_control_mode_t;

#endif
